### ISSUE TITLE
how to build and run

### ISSUE THREAD

**Issue by jianshu93** [larsgottesbueren/gp-ann#1]
Hello @larsgottesbueren,

Thanks for making this graph partitioning idea so useful for large scale graphs. Is there a detailed guidance on how I can reproduce the results from the paper because I have some errors when compiling it, specifically related to the google dense_hash_map.h:

/storage/home/hcoda1/4/jzhao399/scratch/app/gp-ann/external/KaMinPar/kaminpar-shm/datastructures/delta_partitioned_graph.h:10:10: fatal error: google/dense_hash_map: No such file or directory
   10 | #include <google/dense_hash_map>
      |          ^~~~~~~~~~~~~~~~~~~~~~~

I tried to install it here (https://github.com/sparsehash/sparsehash) but it seems I have to include it into my system path to include it, the names is not google/dense_hash_map

Thanks,

Jianshu

**Comment by larsgottesbueren** [comment]
Hi Jianshu,

Appreciate the kind words and your interest in my work!

I believe the easiest way is to go for a user-installation under ```/usr/local/include``` which I can confirm works on my laptop. The ```make install``` command from the sparsehash repo should default to that (I believe). Please double-check their INSTALL readme for details. Otherwise, some distros have it packaged for a system-wide installation, which is a working setup on our server machines.

Once you have the code compiled and the datasets downloaded, the ```experiments.py``` script should take you the rest of the way to result CSVs. Just beware that running everything will take a long time; editing the script to a subset of the experiments should be straight-forward. 

Hope this helps! Please keep the questions coming if more hurdles appear. Another dependency of KaMinPar you will need to install is TBB, btw.

Best,
Lars

**Comment by jianshu93** [comment]
Hi @larsgottesbueren,

Thanks for the quick response, I have no problems with intel-TBB. It is just because I want to ran the whole dataset on a cluster, which I do not have sudo access (so not possible to install to the /use/local/include folder, I may need some time to find out how to modified it in Cmake file to load from specific folder). But I will definitely try it on my laptop first before running on cluster.  Another question I have is how the partition idea compared with cluster first (kmeans as you mentioned), and then build graph for each cluster, query each cluster and then collect results from each cluster, I understand that cluster is not possible for large number of database element, I am thinking of using coreset (for fast and approximate clustering instead of exact clustering, https://arxiv.org/abs/1612.00889) to cluster first because it is faster but in the end, we are still going to search each cluster, so recall will not be comprised but we only need a fraction of memory to do that, without affecting the speed. I understand graph partitioning can be very useful for distributed environment, but the cluster first, graph building later can also be used in a distributed environment. Just some thoughts, no experimental yet for the idea.

Thanks,

Jianshu

**Comment by larsgottesbueren** [comment]
Quick update. Turns out the sparsehash dependency in KaMinPar wasn't really needed (hand-rolled hash tables are faster anyways). I've upgraded this repo to point to the last version of KaMinPar which doesn't use sparsehash. Feel free to give it another go -- remember to update submodules though :)

**Comment by jianshu93** [comment]
thank you very much！
